### ISSUE TITLE
[Suggestion] Clarify Forge minor version or make note of obfuscated methods in current stable release

### ISSUE THREAD

**Issue by nhwhite3118** [TelepathicGrunt/StructureTutorialMod#1]
Looking through the commits on forge, it seems that they only recently deobfuscated the methods for adding features/structures to biomes so stable still has the non-informative names. 

I don't fully understand Microsoft's terms for deobfuscation maps, so I'll just include the method names in the repo which had obfuscated names as of the current stable forge release. It's pretty easy to find their obfuscated names if you know their function and to look for them.

Biome.addStructure
Feature.withConfiguration
ConfiguredFeature.withPlacement
Placement.configure
Structure.withConfiguration

**Comment by TelepathicGrunt** [comment]
It's not actually dependent on the forge version but on the mapping channel you choose in the build.gradle file. If you go into your build.gradle and find a line that looks like this: `mappings channel: 'snapshot', version: '20200508-1.15.1'`, the version number there is what determines the mapping names for your project. 

You can always check http://export.mcpbot.bspk.rs/ for what the latest mapping number to use but 20200508-1.15.1 is the latest right now. Just change that one line, rebuild your project (/gradlew eclipse or the intellij equivalent) a few time, and restart your IDE. Now you'll have the latest mappings!

I'll still add a note about unmapped names to the comments but I hope this helps!
