### ISSUE TITLE
Compatibility with mods

### ISSUE THREAD

**Issue by PermskyKit** [TelepathicGrunt/StructureTutorialMod#11]
Can this be used with Biomes O Plenty? Or maybe there is something similar for this mod to disable the generation of vanilla structures?

**Comment by TelepathicGrunt** [comment]
For anyone else reading this, I gave this person a datapack to disable vanilla structures instead. The datapack is below:
[no_vanilla_structures_datapack.zip](https://github.com/TelepathicGrunt/StructureTutorialMod/files/6385763/no_vanilla_structures_datapack.zip)
