### ISSUE TITLE
No errors, and one of my structures generates, but the other doesn't despite logging it's location in the console?

### ISSUE THREAD

**Issue by misterghast** [TelepathicGrunt/StructureTutorialMod#14]
Hey,
I followed your tutorial for Forge jigsaw structures and it worked like a charm. Unfortunately, after I tried adding a second structure, the entire thing broke. After a bit of tinkering there are no errors and both structures are registered and in DimensionalStructuresSettings.DEFAULTS, and I've set them both up in the numerous registries and lists, but for some reason the second structure does not generate. It simply does not exist in-world, despite the debug log I made for it telling me where it spawned. When I go there, it's just not there, but the first structure is fine. What can cause this? Should I post a git repo or is this a normal occurence? I'm not sure what's happening.

**Comment by TelepathicGrunt** [comment]
Have you tried running it with blame on to print issues? https://www.curseforge.com/minecraft/mc-mods/blame

Is the path to the pool files correct and not typoed? Having the repo would be very helpful for me to help out if Blame doesnt say anything

**Comment by misterghast** [comment]
I was unsure if Blame would do anything given that there's no crashes or errors, but I could try it. Here's the repository: https://github.com/misterghast/DebugStructures

**Comment by misterghast** [comment]
Okay, after trying Blame, it's not doing anything. There's just no errors whatsoever. Plus, when I change the template_pool from the working structure's pool to the non-working structure's, it the working structure still works and generates the new structure's pieces. What is going on?!?!??

**Comment by TelepathicGrunt** [comment]
Both the ancient ruins and desert well structure classes are pointing at the same desertwellcustom pool class. I’m guessing ancient well was suppose to point at the other pool. https://github.com/misterghast/DebugStructures/blob/8b42561032258e31bdbeaad31adf400533daa444/src/main/java/org/hypbase/ghast/cookiesandcream/structures/AncientRuinsStructure.java#L84


The structure spacing for the desert well custom structure is also not being added to the world as it is commented out here https://github.com/misterghast/DebugStructures/blob/8b42561032258e31bdbeaad31adf400533daa444/src/main/java/org/hypbase/ghast/cookiesandcream/CookiesAndCream.java#L84

so the desert well custom is being spawned through the ancient ruins structure which is probably confusing you from what is going on. Try fixing those two things and see if that fixes the issue

**Comment by misterghast** [comment]
I changed both of those things for debug purposes. The behaviour is identical when I remove those changes, except that the actual AncientRuins structures spawn instead. The main issue is that for some reason only the AncientRuins class functions correctly, even if I implement the comment in addDimensionalSpacing.

**Comment by TelepathicGrunt** [comment]
You're missing this.calculateBoundingBox(); at the bottom of DesertWellStructure class before the logging. That method goes through the pieces and creates the bounding box of the entire structure so the game knows when a chunk has parts of the structure in it and should generate it. Without the bounding box calculated for the entire structure, the game never realizes the structure is within a chunk that is generating

**Comment by misterghast** [comment]
AUGHOEU 💀 

thank you, I should have known it would have been something like this.

**Comment by TelepathicGrunt** [comment]
Oh yeah, last thing, you'll probably want to change your isFeatureChunk in the ruins structure to this. It seems it wasn't prevent you from placing the structures in water unless you used the right heightmap
```
	@Override
	protected boolean isFeatureChunk(ChunkGenerator chunkGenerator, BiomeProvider biomeSource, long seed, SharedSeedRandom chunkRandom, int chunkX, int chunkZ, Biome biome, ChunkPos chunkPos, NoFeatureConfig featureConfig) 
	{
		BlockPos centerOfChunk = new BlockPos(chunkX * 16, 0, chunkZ * 16);
		int landHeight = chunkGenerator.getFirstOccupiedHeight(centerOfChunk.getX(), centerOfChunk.getZ(), Heightmap.Type.WORLD_SURFACE_WG);
		IBlockReader columnOfBlocks = chunkGenerator.getBaseColumn(centerOfChunk.getX(), centerOfChunk.getZ());
		BlockState topBlock = columnOfBlocks.getBlockState(centerOfChunk.above(landHeight));
		return topBlock.getFluidState().isEmpty();
	}
```
