### ISSUE TITLE
[Feature request] 1.18.2 changes

### ISSUE THREAD

**Issue by Faboslav** [TelepathicGrunt/StructureTutorialMod#16]
Hello there, i know that 1.18.2 is not released yet, but is it possible to update this repo for that version? Or at least is there an ETA?
Honestly this is probably the only legit/good source for adding new structures to the game, if person does not have any experience with that, at least for me personally this repo is a gamechanger.

**Comment by TelepathicGrunt** [comment]
After I upload repurposed structures and Bumblezone, I’ll update this. What you need to know is 1.18.2 let’s you create custom structures entirely by datapack now so code wise, there’s like nothing you need to do. Though what you can do in code is make the json reference your custom structure class and add new fields to the json that users can change. That’s basically it so like 90% of the 1.18.1 structure tutorial mod can be yeeted and replaced with new json files.

This is what I am doing for repurposed structures right now: 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/tree/1.18.2

This has the vanilla structures entirely done as json:  https://github.com/slicedlime/examples

**Comment by Faboslav** [comment]
Thank you, this was very helpful, i got it working with jsons all right for now while keeping my generate conditions in the code. I have one last question, is it somehow possible to override just `spacing` and `separation` values for the `structure_set` or do i need to make legit class for that and dont use json for this part?

**Comment by TelepathicGrunt** [comment]
You need the entire json file for structure_set. It doesn’t allow for overriding only parts of the json. You can name that json file whatever you want tho as the game is mainly concerned with what structures is put inside it in order to know how to apply the json’s settings to those structures

**Comment by TelepathicGrunt** [comment]
Tutorial is now updated to 1.18.2
