### ISSUE TITLE
Updated code from 1.18.1 to 18.2

### ISSUE THREAD

**Issue by ni-cky** [TelepathicGrunt/StructureTutorialMod#18]
I have updated my structure generation from 1.18.1 to 18.2 according to this github.
I am using fabric.

Now none of my structures generate, and the console does not throw any notable exceptions, does anyone know what the issue could be?

> My code: https://pastebin.com/xfU2CEei

**Comment by TelepathicGrunt** [comment]
Does /locate command show the structures? Are the structures spawning at y = 0 or high up in the sky? Does the log show any errors at all? (Not exceptions. Lines that say any json file was failed to be parsed). And of course, did you make sure there’s no typos in the json files and where you call the start pool?

**Comment by ni-cky** [comment]
Ah, found my mistake >-<
Thanks for helping me realize that I did not see that large parts of the code is now json files. I totally forgot to add most of them.
thank you for your time, and your tutorial is helping a lot!
