### ISSUE TITLE
Half-buried structures in 1.18.2

### ISSUE THREAD

**Issue by MadAlchemist** [TelepathicGrunt/StructureTutorialMod#19]
I am trying to add structure that has both underground and surface parts, but regardless of where was structure block placed initially - on top of structure, below it, or on ground level, structure always spawns with it's bottom on surface. So that instead of well with drowned spawner in it I am getting a weird tower filled with water. Is there any way to adjust structure placement, like it was done in 1.16.5?

**Comment by TelepathicGrunt** [comment]
In 1.18.2, split the structure into two parts. Top part for where you want the piece to rest on land. Bottom piece gets spawned by jigsaw block downward and thus, will spawn underground. The top piece will be the starting pieces

**Comment by TelepathicGrunt** [comment]
Basically similar to how I spawn my basement igloos in 1.18.2. 
https://github.com/TelepathicGrunt/RepurposedStructures/tree/1.18.2/src/main/resources/data/repurposed_structures/structures/igloos

https://github.com/TelepathicGrunt/RepurposedStructures/tree/1.18.2/src/main/resources/data/repurposed_structures/worldgen/template_pool/igloos
