### ISSUE TITLE
Multiple non-overriding abstract methods found in interface net.minecraft.util.registry.RegistryEntry

### ISSUE THREAD

**Issue by DrFreeze2071** [TelepathicGrunt/StructureTutorialMod#20]
I was trying to use this code in my mod, and the IDE wrote an error, that said "Multiple non-overriding abstract methods found in interface net.minecraft.util.registry.RegistryEntry" at the part the config with the location of the start pool is created. I've no idea what this means, or how to solve it, so any help is greatly appreciated. Thank you.

**Comment by DrFreeze2071** [comment]
My bad. Wrong version...

**Comment by TelepathicGrunt** [comment]
I’m guessing you solved this then. But yeah, checking that you’re on the right branch for the Mc/modloader you are on is important since Mojang did refactor structures quite a lot
