### ISSUE TITLE
Feature request: datagen for the structure JSONs

### ISSUE THREAD

**Issue by NoahJelen** [TelepathicGrunt/StructureTutorialMod#23]
Can you please show us how to create the structure JSONs via the data generator?

**Comment by TelepathicGrunt** [comment]
I don’t do datagen so I have no idea how to make those work. So I am of no help sorry. You’ll have to go into the discord for the modloader of your choice and ask them there how to setup datagen for worldgen structure json files since each loader does their datagen differently than others iirc
