### ISSUE TITLE
Automated way to slice up ginourmous structures into 48x48x48 parts?

### ISSUE THREAD

**Issue by allanonmage** [TelepathicGrunt/StructureTutorialMod#24]
I am inspired by When Dugeons Arise, and their praise and referral of you brought me here.  I use your mods/datapacks and their mods/datapacks on my server, and want to take it to the next level by taking some builds I bought and turn them into datapacks (or mods) to generate randomly in my personal server.

I've started watching tutorials, including MCreator stuff, and have been slowly reading Gentleman Revnar's guide for a couple years.  I'd also like to update his structure datapacks to the latest version, but that's a sidequest, and something I might be able to undertake after I get this done.

I will wet my feet with things that can fit into 1 structure block (48x48x48), but I'd also like to do this for some ginourmous builds, for example, I'd like [TrixyBlox's End City](https://youtu.be/E1Ou2BSElto?list=PLOlprUjvBNq4_NHBKAQoK_FdDVfvyLe0Z&t=1446) to pop up all over the end.  It's made entirely of vanilla blocks, but it's the full height of The End, and I think 80 - 100 blocks in diameter, maybe more.  So it will need to be sliced up into structure blocks of 48x48x48.  Does that have to be done manually?  I would presume that there's some kind of tool that can compute that.... maybe I'm overthinking it and Excel will work?

For such large structures with several, maybe even tens of structure blocks, should they be nested/chained, or should there be a clump of structure blocks off to one side accounting for distance from their assigned 48x48x48 chunk? [This video](https://www.youtube.com/watch?v=gLU7E9t8UsM) talks about nesting/chaining them, but only from a using perspective, not a mod or datapack.perspective.

**Comment by TelepathicGrunt** [comment]
You will have to do it manually. Structure blocks do have an offset field so you can keep them all in one corner and offset them to chop up the structure. Then add jigsaw blocks so the pieces spawn the next part of the chopped up structure.

Or you can use Huge Structure Blocks mod to increase range of Structure Block. https://www.curseforge.com/minecraft/mc-mods/huge-structure-blocks

You are still limited to an approximately 112 block radius tho allowed for the structure

**Comment by allanonmage** [comment]
oooooo, that mod is definitely worth looking into, thanks!
