### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by thrasos-dev** [TelepathicGrunt/StructureTutorialMod#25]
There seem to be some missing images in the [tutorial](https://github.com/TelepathicGrunt/StructureTutorialMod/blob/1.20.2-Neoforge-Jigsaw/README.md).

<img width="712" alt="Screenshot 2024-03-18 at 16 51 22" src="https://github.com/TelepathicGrunt/StructureTutorialMod/assets/100732009/e879ca42-40d6-44d2-b7c3-9b6a7930fb3a">

<img width="711" alt="Screenshot 2024-03-18 at 16 51 31" src="https://github.com/TelepathicGrunt/StructureTutorialMod/assets/100732009/c92b08f7-09fe-4ddd-b05b-ad03fe4af7f1">

**Comment by TelepathicGrunt** [comment]
fixed
