### ISSUE TITLE
Question: forced structure rotation

### ISSUE THREAD

**Issue by Quatryl23** [TelepathicGrunt/StructureTutorialMod#27]
Is there a way to force the rotation of structures?
I make a datapack but there is no json argument for rotation. But if my structures are rotated, they contain glitched blocks like the Create mod train track which can´t really rotate. The only solution would be disabling rotation of the structure.

**Comment by TelepathicGrunt** [comment]
I think the best ideal solution is report the issue to the create devs and ask them to fix their block rotation. That’s ultimately a mod issue. The rotation is randomly chosen within the jigsaw piece generator code which is not easy to adjust.

**Comment by Quatryl23** [comment]
Thank you for your quick answer. I reported the issue and hope they'll fix it.

**Comment by Quatryl23** [comment]
Sorry to disturb again, but unfortunately, they seem to not fix this soon and when I set my mind to something, I'm determined to see it through.
So I found your answer at r/feedthebeast and clicked the link where you said "Or you can copy the JigsawPlacement.addPieces method and just remove the start piece rotation part of it". I skimmed the code, although I don't really know how Java works, but I didn't see something like "start piece rotation"
Would you mind explaining that?

**Comment by TelepathicGrunt** [comment]
It's the line that is getting a random rotation in jigsawPlacement's addPieces method. But requires copying the whole method to your own code and setting the rotation to a specific kind.
![image](https://github.com/TelepathicGrunt/StructureTutorialMod/assets/40846040/0a62c56f-e61e-4bc1-9491-e635221d0ebe)

**Comment by Quatryl23** [comment]
Which file is that?

**Comment by TelepathicGrunt** [comment]
net\minecraft\world\level\levelgen\structure\pools\JigsawPlacement.java

**Comment by Quatryl23** [comment]
I can´t find it

**Comment by TelepathicGrunt** [comment]
What Minecraft version are you on and are you using yarn mappings? 

(This class is what SkyStructure Java file is calling for creating the piece layout)

**Comment by Quatryl23** [comment]
Minecraft Version 1.20.1 with Forge Modpack

**Comment by Quatryl23** [comment]
![Unbenannt](https://github.com/TelepathicGrunt/StructureTutorialMod/assets/170469614/d312bba4-5626-4a05-98df-2ca1d780ff23)

**Comment by Quatryl23** [comment]
That´s the folder of the modpack

**Comment by Quatryl23** [comment]
![Unbenannt](https://github.com/TelepathicGrunt/StructureTutorialMod/assets/170469614/d02c0fc9-aed9-425f-bf5e-ed43ab795c0a)
And this is the world folder I placed my datapack in

**Comment by TelepathicGrunt** [comment]
Uhh. This StructureTutorialMod is for modders. Not players or packmakers. What I was describing is something only a modder can do by writing custom code to change how a structure generates. A datapack has no ability to change direction of a structure.

**Comment by TelepathicGrunt** [comment]
A modder would have their own structure class and basically unwrap out this method and change the rotation for their structure type. Then call that structure type in their Structure json file.
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/187fc889b840f273bec64f9d811e8850b510afca/src/main/java/com/telepathicgrunt/structuretutorial/structures/SkyStructures.java#L118

This would have to be done by a modder since the mod will need to be compiled and ran to in order to work in production.

**Comment by Quatryl23** [comment]
Ok, I thought it would be something easy to change in some files in addition to the datapack, but if I have to make a mod myself, then I think I can´t do it.
thank you anyway for the help

**Comment by TelepathicGrunt** [comment]
Yeah it’s a limitation of the vanilla structure json system. Sorry about that
