### ISSUE TITLE
Empty or none existent pool

### ISSUE THREAD

**Issue by Zathrox** [TelepathicGrunt/StructureTutorialMod#7]
Hello, I've followed this tutorial for 1.16 jigsaw version in the latest forge version, so 1.16.5 - 36.0.55, I've read and amended all the code into my current mod but i'm getting this error:

Empty or none existent pool: structure_tutorial:run_down_house/side_pool

now both my start and side pools json have been changed to my modId, i've changed all instances of it in the code where you had your modId but its still locating the structure_tutorial folder which doesn't exist somehow..

The left side of the structure spawns perfectly, its just for some reason locating a different folder structure for the side_pool.json

Any ideas? I can provide structure setup, if you need.

**Comment by Zathrox** [comment]
I think i've found out the issue, its because the side_pool is loaded from the jigsaw, it was hard-saved to load the structure_tutorial:run_down_house, which on my mod doesn't exist. So I loaded up all 3 structures and changed it to explorercraft, reloaded the mod and it worked! 

I was thinking it might be worth clarifying that in order to test/use the NBT files provided, you need to load the structure files directly and modify the jigsaw pieces and that changing the JSON files isn't enough?

Otherwise, this is an absolutely amazing tutorial, really clear and simply to use, now i'm going to try and convert my old hard-coded dungeon into an jigsaw one :D

**Comment by TelepathicGrunt** [comment]
Yeah there's no real good way for me to mention to people to change the jigsaw block itself But thank you for the feedback! I'll try and see if I can squeeze it in somewhere
