### ISSUE TITLE
NullPointException when i start a server

### ISSUE THREAD

**Issue by Scout24HD** [TelepathicGrunt/StructureTutorialMod#9]
Hi i have tryed this system on a server and i get a nullpointException
i hope you can help me :)
lastlog:
[latest.log](https://github.com/TelepathicGrunt/StructureTutorialMod/files/6370475/latest.log)

**Comment by TelepathicGrunt** [comment]
```
Caused by: java.lang.NullPointerException
	at net.minecraft.world.gen.feature.jigsaw.JigsawManager.func_242837_a(SourceFile:266) ~[?:?]
	at net.mrscauthd.boss_tools.world.structure.AlienVillageStructure$Start.func_230364_a_(AlienVillageStructure.java:161) ~[boss_tools:1.0]
```
	
Looks like Space-Bosstools broke and is crashing. They probably made a typo on the path to their start pool which causes the game to crash. Try make an issue report to them with that log and they may be able to fix it soon

**Comment by TelepathicGrunt** [comment]
oh wait a second, this is structure tutorial mod, not repurposed structures. oh sorry, you were asking for help

**Comment by Scout24HD** [comment]
no problem

**Comment by TelepathicGrunt** [comment]
this null error tends to be caused when the path specified here doesn't actually point to a pool file
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/dd6dc50bc6cf243021f599f40e721daa5f4e120e/src/main/java/com/telepathicgrunt/structuretutorial/structures/RunDownHouseStructure.java#L188

For me, ```new ResourceLocation(StructureTutorialMain.MODID, "run_down_house/start_pool")``` resolves to ```data/structure_tutorial/worldgen/template_pool/run_down_house/start_pool.json```. And that file is found here: 
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/1.16.3-Forge-jigsaw/src/main/resources/data/structure_tutorial/worldgen/template_pool/run_down_house/start_pool.json

**Comment by TelepathicGrunt** [comment]
check to see that you specified the right path and that the pool file is under resources/data and not resources/assets

**Comment by Scout24HD** [comment]
ok sec

**Comment by Scout24HD** [comment]
yea it is the right path

**Comment by TelepathicGrunt** [comment]
is your code on github so I can check it out? Could be a number of things that causes the issue.

**Comment by Scout24HD** [comment]
no its not, but i think i have found the error (seci check it)

**Comment by Scout24HD** [comment]
thx that you try me to help 👍 
i found the bug :)

**Comment by TelepathicGrunt** [comment]
nice! Sorry about the confusion earlier and good luck!
